name = "bevy-butler"
description = "A library for simplifying Plugin definitions by registering systems, events and resources at declaration."
link = "https://github.com/TGRCdev/bevy-butler"
image = "bevy-butler.png"
crate = "bevy-butler"